### ISSUE TITLE
Bool Nodes not working

### ISSUE THREAD

**Issue by Aljnk** [evanspearman/ComfyMath#6]
I am trying to add your Bool Node (any) - it does not appear in the workflow at all.
Probably the problem is that your `Classes `don't have a `RETURN_NAMES `parameter.

**Comment by evanspearman** [comment]
I believe this was caused by ComfyMath naming the type "BOOL" whereas ComfyUI itself has now standardized on "BOOLEAN" (I don't believe ComfyUI had any sort of booleans when I initially implemented this, but I may be mistaken). I've changed this to be "BOOLEAN" in ComfyMath now.

`RETURN_NAMES` is an optional property so shouldn't cause an issue.
